### ISSUE TITLE
Scipy

### ISSUE THREAD

**Issue by freakboy3742** [beeware/mobile-forge#10]
### What is the PyPI name of the package you would like to see added?

scipy

### Additional details

Major blocker is availability of a Fortran compiler that can target iOS

**Comment by freakboy3742** [comment]
Via @ydesgagn - he reports that it's possible to get flang working for iOS by running it through a Docker container.

Use this docker file to prepare a flang image:
```
FROM ubuntu:jammy

# persistent dependencies
RUN set -eux ; \
    apt-get -y update ; \
    apt-get -y --no-install-recommends install ca-certificates build-essential wget libncurses5 ;

# flang
RUN wget https://github.com/flang-compiler/flang/releases/download/flang_20190329/flang-20190329-x86-70.tgz ; \
    tar -xvzf *.tgz ; \
    rm -f *.tgz ; \
    ldconfig ;
```

Then, use this script (`flang.sh`) to execute the container:
```
#!/usr/bin/env bash

# shellcheck disable=SC2068
docker exec -it flang /root/host/proxy.sh "${PWD}" ${@}
cp -rf inbox/* "${PWD}" &> /dev/null
rm -rf inbox/* &> /dev/null
```

The replacement `gfortran` is a Python script that fixes command line arguments and calls `flang.sh`:
```
#!/usr/bin/env python3

import sys
import os
import shlex
import subprocess
import string
import random
import shutil

def join_args(args):
    return ' '.join(shlex.quote(x) for x in args)

if "-dumpversion" in sys.argv:
    print("10.2.0")
    sys.exit(0)

arguments = []
sys_args = sys.argv
del sys_args[0]

try:
    for arg in os.environ["ARCHFLAGS"].split(" "):
        sys_args.append(arg)
except KeyError:
    pass

if "-h" in sys_args or "--help" in sys_args:
    print("The running executable emulates a Fortran compiler. If '-arch arm64' is passed, the compiler will produce an arm64 object file for iOS from the passed source. If not, gfortran located in '/opt/homebrew/bin/' will be executed.")
    print("Because flang runs in a Docker container, only files under '/Users/', '/var/folders' or '/Library' can be compiled.")
    sys.exit(0)

all_args_are_object_files = True

for arg in sys_args:

    if os.path.isfile(arg) and not arg.endswith(".o"):
        all_args_are_object_files = False

if (not "-c" and not all_args_are_object_files) in sys_args or not "-arch arm64" in " ".join(sys_args):
    print("The executed Fortran compiler only supports producing object files for iOS arm64, falling back to gfortran.", file=sys.stderr)
    print("To compile sources for iOS arm64, make sure to add -arch arm64 and -c.", file=sys.stderr)
    sys.exit(os.system(shlex.join(["/opt/homebrew/bin/gfortran"]+sys_args)))

if "-bundle" in sys_args or all_args_are_object_files:
    args = ["clang", "-undefined", "dynamic_lookup", "-shared"]
    try:
        for arg in os.environ["LDFLAGS"].split(" "):
            args.append(arg)
    except KeyError:
        pass
    for arg in sys_args:
        if arg != "-bundle":
            args.append(arg)
    
    command = shlex.join(args)
    sys.exit(os.system(command))

def convert_to_docker_path(arg):
    if arg.startswith("/"):
        arg = "/¡"+arg
    else:
        arg = os.path.join(os.getcwd(), arg)
    
    return arg

the_previous_parameter_was_dash_o = False
the_previous_parameter_was_dash_c = False
the_previous_parameter_was_dash_arch = False
output_path = None
source = None

for arg in sys_args:

    if arg == "-c":
        the_previous_parameter_was_dash_c = True
    elif the_previous_parameter_was_dash_c:
        the_previous_parameter_was_dash_c = False
        source = arg

    if arg == "-o":
        the_previous_parameter_was_dash_o = True
        continue
    elif the_previous_parameter_was_dash_o:
        the_previous_parameter_was_dash_o = False
        output_path = arg
        continue

    if arg == "-arch":
        the_previous_parameter_was_dash_arch = True
        continue
    elif the_previous_parameter_was_dash_arch:
        the_previous_parameter_was_dash_arch = False
        continue

    if arg == "-fallow-argument-mismatch":
        continue

    if os.path.exists(arg):
        arg = convert_to_docker_path(arg)
    if arg.startswith("-I"):
        path = arg.split("-I")[-1]
        arg = "-I"+convert_to_docker_path(path)

    if arg.startswith("/¡"):
        arg = arg[2:]

    arguments.append(arg)

if output_path is None and source is not None:
    parts = source.split(".")
    del parts[-1]
    output_path = os.getcwd()+"/"+".".join(parts)+".o"

if os.path.isfile(output_path):
    sys.exit(0)

print(output_path)

dir = os.path.dirname(os.path.abspath(__file__))
cwd = os.getcwd()

arguments.insert(0, os.path.abspath(os.path.join(dir, "flang.sh")))
arguments.insert(1, "--save-temps")
flang_command = join_args(arguments)

inbox = os.path.join(cwd, ".inbox"+''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5)))

try:
    os.mkdir(inbox)
except FileExistsError:
    pass

os.chdir(inbox)

os.system(flang_command)
file_path = None

for file in os.listdir("."):
    if not file.endswith(".ll"):
        try:
            os.remove(file)
        except FileNotFoundError:
            pass
    else:
        file_path = os.path.join(os.getcwd(), file)

os.chdir(cwd)
llc = [os.path.join(dir, "llc"), "-mtriple=arm64-apple-ios", "-filetype=obj", file_path, "-o", output_path]
subprocess.run(llc, stdout=None, stderr=None)

shutil.rmtree(inbox)
```

The `proxy.sh` that is referenced is:
```
#!/usr/bin/env bash

cd /root/host || exit
cd "${1}" || exit
flang "${@:2}"
```

**Comment by mhsmith** [comment]
> Major blocker is availability of a Fortran compiler that can target iOS

@meow464: You used to have a good summary of this at https://meow464.neocities.org/Fortran/state-of-fortran-on-ios. Is there some reason why you've taken it down?

**Comment by meow464** [comment]
The url changed https://meow464.neocities.org/blog/state-of-fortran-on-ios/

I added support for iOS cross compilation on LFortran but it still can't compile scipy and lapack. Both are being actively worked on.

https://github.com/lfortran/lfortran/issues/1251

**Comment by meow464** [comment]
I will add instructions for cross compiling for iOS, there was a pull request for that but I forgot about it.

It's not complicated, just cross compile the runtime with a iOS cmake toolchain file then use --target=apple-iphone-ios

**Comment by meow464** [comment]
@freakboy3742 is that the old or new flang?

**Comment by freakboy3742** [comment]
@meow464 I can't say I know - I opened this ticket so I had a store of some details that @ydesgagn provided to me; he may be able to comment. If I had to guess based on the Dockerfile, it seems to be using flang 20190329.

**Comment by meow464** [comment]
That's the old flang also known as flang classic, it's based on the open sourced PGI compiler and it has a problem generating the apple-arm ABI. I spent some 6 months working on it in 2021 but couldn't fix it. 
Yes it can generate code and some stuff will work but other stuff will crash.

The problem is with variadic arguments. On arm they should be put on registers until none are available and then on the stack. On apple they should all be put on the stack.

The flang intrinsic functions are written in C and compiled with the apple abi (as they should) but the fortran code is compiled with the apple abi.

**Comment by freakboy3742** [comment]
Ah - good to know. Thanks for those details. "Run flang through Docker" seemed like a neat trick, but it also seemed like *just* enough of a neat trick that there was very likely a land mine in waiting.

**Comment by freakboy3742** [comment]
It's worth noting that [Quansight recently blogged about getting flang working with SciPy](https://labs.quansight.org/blog/building-scipy-with-flang).

**Comment by ydesgagn** [comment]
@meow464 We are executing unit tests on an iPad M2 and they all pass for Scipy. Can you be more specific on `has a problem generating the apple-arm ABI`? Also we have an iPad only application using written in Swift accepted by the Apple Store extensively calling Python 3.11 with numpy, scikit-learn and scipy and all the reported bugs we got so far are due to our failure in our code. Nothing in Python, numpy, scikit-learn and scipy.

@freakboy3742 one of my guy is about to PR in https://github.com/beeware/mobile-forge to add scikit-learn. Will do more after that and we can try Scipy if you think the Docker way is not too hacky.

**Comment by mhsmith** [comment]
> Can you be more specific on `has a problem generating the apple-arm ABI`?

There are some more details and links [here](https://meow464.neocities.org/blog/state-of-fortran-on-ios/), but they may not be up to date.

**Comment by serhii-vlasiuk** [comment]
For 3.11
Added recipes/scipy/meta.yaml
package:
  name: scipy
  version: 1.11.3

Getting error
ERROR: Could not find a version that satisfies the requirement numpy==1.23.2 (from versions: 1.26.0)
ERROR: No matching distribution found for numpy==1.23.2
Traceback (most recent call last):
  File "/Users/svlas/ydesgagn/github/mobile-forge/venv3.11/bin/forge", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/svlas/ydesgagn/github/mobile-forge/src/forge/__main__.py", line 205, in main
    builder.prepare(clean=args.clean and (p == 0))
  File "/Users/svlas/ydesgagn/github/mobile-forge/src/forge/build.py", line 407, in prepare
    self.cross_venv.pip_install(
  File "/Users/svlas/ydesgagn/github/mobile-forge/src/forge/cross.py", line 375, in pip_install
    self.run(
  File "/Users/svlas/ydesgagn/github/mobile-forge/src/forge/cross.py", line 362, in run
    return subprocess.run(args, **final_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/svlas/ydesgagn/github/Python-Apple-support/install/macOS/macosx/python-3.11.6/lib/python3.11/subprocess.py", line 575, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'pip', 'install', '--disable-pip-version-check', '--only-binary', ':all:', '--find-links', '/Users/svlas/ydesgagn/github/mobile-forge/dist', 'build', 'meson-python>=0.12.1,<0.15.0', 'Cython>=0.29.35,<3.0', 'pybind11>=2.10.4,<2.11.1', 'pythran>=0.12.0,<0.15.0', "numpy==1.22.0; platform_machine=='loongarch64'", "numpy==1.22.3; python_version=='3.9' and platform_system=='Windows' and platform_python_implementation != 'PyPy'", "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'", "numpy==1.21.6; python_version=='3.9' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'", "numpy==1.21.6; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'", "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'", "numpy>=1.26.0,<1.27.0; python_version=='3.12'", "numpy; python_version>='3.9' and platform_python_implementation=='PyPy'", "numpy>=1.26.0; python_version>='3.13'"]' returned non-zero exit status 1.

**Comment by freakboy3742** [comment]
It seems to me that the error message is telling you exactly what is going on:
```
No matching distribution found for numpy==1.23.2
```

You need to have numpy 1.23.2 available for installation.

On 3.11, 1.23.2 is a special version of numpy - it's the oldest supported version. A lot of numpy-related tooling will deliberately build against the "oldest-supported-numpy" target to ensure maximum ABI compatibility. You'll need to build this version first (`forge iOS numpy:1.23.2`)

**Comment by h-vetinari** [comment]
You can patch out the dependence on `oldest-supported-numpy` and just use the oldest one you have available. It's just a question of being conservative with ABI support, it's not like that exact version is needed to build

**Comment by freakboy3742** [comment]
Sure, you *can* patch it out, but that's not how official Scipy builds are made. The goal of this project is to provide a stepping stone towards Scipy providing its own official iOS packages (although, to be clear - that's a way off). If we're going to patch SciPy, the patches are going to be specific to getting a successful build on iOS, not hacks to get around inconveniences that have no chance of being upstreamed.

Plus - it's not like it's hard to build numpy 1.23.2. The recipe is already there.

**Comment by hyazel** [comment]
It's super cool that you're working on it, thanks. 

I was just struggling making `scipy` work on an iOS project. 

Meanwhile I'll take a look on the mobile forge mechanism.

**Comment by hyazel** [comment]
I tried to `forge iOS scipy` with numpy (**1.23.3**) already compiled on my machine but I have the following error : 

```
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
```
seems to be related to the Fortran compilation you mentionned earlier. 

Do you have an ongoing PR @freakboy3742 or something we can help you on ? 

@ydesgagn Hello ! Could you describe the all process to compile `scipy` on Docker ? 

Thanks !

**Comment by ydesgagn** [comment]
@hyazel will create a PR this weekend so you can try with the proper tools available.

**Comment by freakboy3742** [comment]
> Do you have an ongoing PR @freakboy3742 or something we can help you on ?

Everything I have in progress for mobile forge is open on PRs on this repo at present. I haven't tackled BLAS/LAPACK at all.

**Comment by ydesgagn** [comment]
Here the PR https://github.com/beeware/mobile-forge/pull/28

Really sorry for not responding sooner. I'm no longer familiar with the code the repo but if somebody can add the recipe with the instructions in the PR, this was working for me in the past.

I will try to help if you run out in any trouble.

**Comment by freakboy3742** [comment]
@ydesgagn Thanks for that PR. I'm not sure when I'll get a chance to take a deep look at it myself, but if anyone else wants to dig into the problem, they've now got all the pieces.

**Comment by pasdeloup** [comment]
Thanks @ydesgagn 
A teammate is already working on it (I'm on Linux not Mac), we were trying to figure out what you did from your other repo
https://github.com/Cloud-Officer/ios-frameworks but this PR will help a lot!

So you don't need to build first BLAS/LAPACK?

**Comment by ydesgagn** [comment]
No I did not built it. I just pointed scipy at the homebrew ARM64 version and linked with that. But I know @freakboy3742 is not a big fan of homebrew dependencies.

**Comment by freakboy3742** [comment]
I'm not a fan because homebrew libraries have a history of breaking iOS builds because they're linked against macOS system libraries, not iOS system libraries (gettext is a particularly recurring culprit here)

If the homebrew build of BLAS/LAPACK *does* work on iOS, then it should be possible to port the recipe directly to mobile-forge, except *explicitly* using iOS compilers and libraries, rather than relying on a lack of problematic symbols. We already do builds for libraries like libpng and libjpeg; if we've got a working recipe, I can't see why BLAS/LAPACK would be any different.

**Comment by mhsmith** [comment]
It looks like there are already [official BLAS and LAPACK builds from Apple](https://developer.apple.com/documentation/accelerate?language=objc) (see OS support indicators at the top). Maybe we could use these, although SciPy might need a bit of help to find them.

**Comment by noelmullankuzhy** [comment]
@pasdeloup Hi, do you have any progress on building SciPy wheel for iOS?. @ydesgagn Could you please share the working SciPy wheel that you have built, while we  figure out how to make build on out own? Thank you.

**Comment by michaeleisel** [comment]
SciPy works well with Apple's BLAS/LAPACK library, Accelerate. It can be built from the SciPy repo with `python dev.py build --with-accelerate`. This strategy is also what allows NumPy to work. However, SciPy also has its own Fortran files outside of BLAS/LAPACK, such as in `scipy/integrate/quadpack`. This is where we still need a Fortran compiler.

It appears that the Pyto iOS app supports SciPy, and that app's author has found a way to compile Fortran code with Docker, similar to the approach discussed above. Their repo: https://github.com/ColdGrub1384/fortran-ios . Presumably, this is the tool they're using for SciPy for Pyto.

@ColdGrub1384 are you able to share a more fleshed-out list of steps for compiling these Fortran files for SciPy? For example, how did you deal with things like, the linking in of `/opt/homebrew/Cellar/gcc/14.1.0_2/lib/gcc/current` to the Fortran .so files, did you cross-compile that library as well?

Another strategy would be to take the .so files for macOS and just change their binary metadata so that they look like iOS binaries, and then use them like that. This is a little weird, but I'm told that it's pretty safe.

**Comment by meow464** [comment]
Scipy used to support Accelerate but no longer does, the reasons are listed here: https://github.com/scipy/archive/blob/main/wiki/dropping-accelerate-support.md

**Comment by freakboy3742** [comment]
@meow464 Are you sure that information is current? I know it was definitely true in the SciPy v1.2 timeframe (which is where that document comes from), but conversations I've had recently suggest that that the SciPy team either have moved, or are planning to move back to Accelerate because the bugs in the Accelerate implementation of BLAS/LAPACK have become less of a problem than the general problem of trying to get a Fortran compiler that works.

**Comment by meow464** [comment]
I do not know if it's current and good to hear they are considering Accelerate again.

**Comment by h-vetinari** [comment]
Since apple introduced an updated LAPACK in MacOS 13.3, we have readded explicit support, see https://github.com/scipy/scipy/pull/19816
